# Generated by Django 4.0.6 on 2022-07-21 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModuleTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_id_tag', to='Testapp.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_tag_user_id', to=settings.AUTH_USER_MODEL)),
                ('module_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_id_tag', to='Testapp.coursemodule')),
                ('tag', models.ManyToManyField(to='Testapp.coursemoduletag')),
            ],
        ),
        migrations.CreateModel(
            name='CourseModuleAssignee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_module_assignee', to=settings.AUTH_USER_MODEL)),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_assignee', to='Testapp.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignee_user_id', to=settings.AUTH_USER_MODEL)),
                ('module_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_assignee', to='Testapp.coursemodule')),
            ],
        ),
    ]
