# Generated by Django 4.0.6 on 2022-07-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testapp', '0002_coursemoduletag_coursemoduleassignee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemoduletag',
            name='tag',
        ),
        migrations.AddField(
            model_name='coursemoduletag',
            name='tag',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
